openapi: 3.0.0
info:
  title: Secret Keeper Api
  description: An api that helps manage your secrets.
  version: 1.0.0
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: credentials
    description: Manage your credentials
paths:
  /credentials:

    get:
      tags:
        - credentials
      summary: Get credentials
      operationId: getCredentials
      description: Get all the credentials that matche the research criteria.
      parameters:
        - schema:
            type: string
          in: query
          name: url
        - schema:
            type: string
          in: query
          name: username
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CredentialDetails'
              examples: {}
            application/xml:
              schema:
                type: object
                properties: {}

components:
  schemas:

    CredentialDetails:
      type: object
      properties:
        id:
          type: integer
        url:
          type: string
        username:
          type: string
        password:
          type: string